<div class="page-header">
    <h1>Cadastrar Produto</h1>
</div>

<?php if($this->error !== null) : ?>
    <div class="alert alert-danger" role="alert">
        <?=$this->error ?>
    </div>
<?php endif; ?>


<form style="max-width: 500px; margin: 0 auto 50px;" method="post">
    <div class="form-group">
        <label for="produto-nome">Nome do produto</label>
        <input name="produto-nome" type="text" class="form-control" id="produto-nome" value="<?=($this->produto !== null ? $this->produto->getNome() : '') ?>">
    </div>

    <div class="form-group">
        <label for="produto-valor">Valor do produto</label>
        <input name="produto-valor" type="number" min="0.1" step="any" class="form-control" id="produto-valor" value="<?=($this->produto !== null ? $this->produto->getValor() : '') ?>">
    </div>

    <div class="form-group">
        <label for="produto-categoria">Categoria do produto</label>
        <select name="produto-categoria" id="produto-categoria" class="form-control">
            <?php foreach($this->categorias as $categoria) : ?>
                <option value="<?=$categoria->getId() ?>" <?=($this->produto !== null && $this->produto->getCategoria() == $categoria->getId() ? 'selected' : '') ?>>
                    <?=$categoria->getNome() ?>
                </option>
            <?php endforeach; ?>
        </select>
    </div>

    <div class="form-group">
        <label for="produto-descricao">Descrição do produto</label>
        <textarea id="produto-descricao" name="produto-descricao" class="form-control" style="height: 200px; resize: none;"><?=($this->produto !== null ? $this->produto->getDescricao() : '') ?></textarea>
    </div>

    <div class="form-group">
        <label for="produto-imagem">Imagem do Produto</label>
        <input name="produto-imagem" type="file" class="form-control" id="produto-imagem">
        <div id="produto-thumbnail" class="thumbnail">
            <img src="https://placeholdit.imgix.net/~text?txtsize=33&txt=900%C3%97500&w=500&h=500">
        </div>
    </div>

    <div style="text-align: center">
        <button name="produto-salvar" type="submit" class="btn btn-success">Salvar</button>
        <a class="btn btn-danger" href="<?=$this->url('produtos', 'index', array(), true) ?>">Voltar</a>
    </div>
</form>
