<div class="page-header">
    <h1>Gerenciar Categorias <small>total <?=count($this->categorias) ?></small></h1>
</div>
<div class="panel panel-default">
    <div class="panel-heading">
        Categorias cadastradas
        <a href="<?=$this->url('categorias', 'create', array(), true) ?>" class="btn btn-success categorias-action-create">
            <span class="glyphicon glyphicon-asterisk" aria-hidden="true"></span>
            <span class="hidden-xs">Cadastrar</span>
        </a>
    </div>
    <table class="table table-striped table-hover">
        <thead>
            <tr>
                <th class="categorias-col-id">#</th>
                <th class="categorias-col-nome">Nome</th>
                <th class="categorias-col-action">Ações</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($this->categorias as $categoria) : ?>
            <tr>

                <td class="categorias-col-id"><?=$categoria->getId() ?></td>
                <td class="categorias-col-nome"><?=$categoria->getNome() ?></td>

                <td class="categorias-col-action">
                    <a href="<?=$this->url('categorias', 'update', array('categoria_id' => $categoria->getId()), true) ?>" class="btn btn-primary" title="Editar Produto">
                        <span class="glyphicon glyphicon-edit" aria-hidden="true"></span>
                        <span class="hidden-xs">Editar</span>
                    </a>
                    <a href="<?=$this->url('categorias', 'delete', array('categoria_id' => $categoria->getId()), true) ?>" class="btn btn-danger" title="Remover Produto">
                        <span class="glyphicon glyphicon-trash" aria-hidden="true"></span>
                        <span class="hidden-xs">Remover</span>
                    </a>
                </td>
            </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
</div>
