<div class="page-header">
    <h1>Editar Categoria <small>(#<?=($this->categoria !== null ? $this->categoria->getId() : '0') ?>)</small></h1>
</div>

<?php if($this->error !== null) : ?>
    <div class="alert alert-danger" role="alert">
        <?=$this->error ?>
    </div>
<?php endif; ?>


<form method="post">
    <div class="form-group">
        <label for="categoria-nome">Nome da categoria</label>
        <input name="categoria-nome" type="text" class="form-control" id="categoria-nome" value="<?=($this->categoria !== null ? $this->categoria->getNome() : '') ?>">
    </div>

    <input type="hidden" name="categoria-id" value="<?=($this->categoria !== null ? $this->categoria->getId() : '') ?>">

    <div style="text-align: center">
        <button name="categoria-salvar" type="submit" class="btn btn-success">Salvar</button>
        <a class="btn btn-danger" href="<?=$this->url('categorias', 'index', array(), true) ?>">Voltar</a>
    </div>
</form>
