<?php
    use Admin\Model\Categoria;
    $route = $this->app()->request()->getRoute();
    $isHome = $route == '/' || $route == '/shop/index';
    $isCart = !$isHome && ($route == '/cart' || $route == '/cart/index');
    $cartCount = count($_SESSION['cart']);
    $categoriaId = (int) $isHome ? -1 : $this->app()->request()->getQuery('categoria', -1);
    $buscar = (int) $isHome ? '' : $this->app()->request()->getQuery('buscar', '');
    $baseUri = $this->app()->request()->getBaseUri();
    $categorias = Categoria::findBy(array('removido' => false));
?>
<!DOCTYPE html>
<html>
    <head>
        <meta charset="<?=$this->charset ?>">
        <title><?=$this->title ?></title>
        <meta charset="utf-8">

        <!--Styles -->
        <link rel="stylesheet" href="<?=$baseUri ?>/css/bootstrap.min.css">
        <link rel="stylesheet" href="<?=$baseUri ?>/css/shop.css">

        <!-- Scripts -->
        <script type="text/javascript" src="<?=$baseUri ?>js/jquery-2.1.4.min.js"></script>
        <script type="text/javascript" src="<?=$baseUri ?>js/bootstrap.min.js"></script>
        <script type="text/javascript" src="<?=$baseUri ?>js/navbar.js"></script>
    </head>
    <body>

        <nav class="navbar navbar-custom">
            <div class="container-fluid">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-links" aria-expanded="false">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="<?= $baseUri.'index.php' ?>">Brand</a>
                </div>
                <div class="collapse navbar-collapse" id="navbar-links">
                    <ul id="navbar-links-container" class="nav navbar-nav navbar-left" style="position: absolute; left: 79px;">
                        <li <?= $isHome ? 'class="active"' : '' ?> >
                            <a href="<?= $baseUri.'index.php' ?>">Início</a>
                        </li>
                        <?php foreach ($categorias as $item) : ?>
                            <li <?=$item->getId() == $categoriaId ? 'class="active"' : '' ?> >
                                <a href="<?=$this->url('shop', 'categoria', array('categoria' => $item->getId()), true) ?>">
                                    <?=$item->getNome() ?>
                                </a>
                            </li>
                        <?php endforeach; ?>
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                                <span class="sr-only">Toggle navigation</span>
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span>
                            </a>
                            <ul class="dropdown-menu"></ul>
                        </li>
                    </ul>
                    <ul class="nav navbar-nav navbar-right">
                        <li id="navbar-cart" <?= $isCart ? 'class="active"' : '' ?> >
                            <a href="<?=$this->url('cart', 'index', array(), true) ?>">
                                <span class="glyphicon glyphicon-shopping-cart" aria-hidden="true"></span>
                                <span class="visible-xs-inline">Carrinho</span>
                                <?php if($cartCount > 0) : ?>
                                    <span class="badge visible-xs-inline"><?=$cartCount ?></span>
                                <?php endif; ?>

                            </a>
                            <?php if($cartCount > 0) : ?>
                                <span class="cart-badge hidden-xs"><?=$cartCount ?></span>
                            <?php endif; ?>
                        </li>
                    </ul>
                    <form id="navbar-search" class="navbar-form navbar-right" role="search" action="<?=$this->url('shop', 'pesquisa', array(), true) ?>" method="get">
                        <div class="form-group">
                            <input type="text" name="buscar" class="form-control" placeholder="Procurando alguma coisa?" value="<?=$buscar ?>">
                            <button type="submit" class="btn">
                                <span class="glyphicon glyphicon-search" aria-hidden="true"></span>
                            </button>
                        </div>
                    </form>
                </div>
            </div>
        </nav>
        <div id="main-container" class="container container-fluid">
            <?=$this->content ?>
        </div>
    </body>
</html>
