<?php
    $baseUri = $this->app()->request()->getBaseUri();
    $currentController = $this->app()->getControlerName();
    $menus = array(
        array(
            'label' => 'Loja',
            'url' => $baseUri.'index.php',
            'actived' => false
        ),
        array(
            'label' => 'Categorias',
            'url' => $this->url('categorias', 'index', array(), true),
            'actived' => $currentController === 'categorias'
        ),
        array(
            'label' => 'Produtos',
            'url' => $this->url('produtos', 'index', array(), true),
            'actived' => $currentController === 'produtos'
        ),
    );
?>
<!DOCTYPE html>
<html>
    <head>
        <meta charset="<?=$this->charset ?>">
        <title><?=$this->title ?></title>

        <!--Styles -->
        <link rel="stylesheet" href="<?=$baseUri ?>css/bootstrap.min.css">
        <style type="text/css">
            .navbar{
                border-radius: 0;
            }

            .produtos-col-id"{
                width: 5%;
            }

            .produtos-col-nome{
                width: 40%;
            }

            .produtos-col-valor{
                width: 15%;
            }

            .produtos-col-action{
                width: 25%;
            }

            .produtos-col-categoria{
                width: 15%
            }

            th.produtos-col-action{
                text-align: center;
            }

            td.produtos-col-action{
                text-align: center;
                padding: 3px 0 !important;
            }

            td.produtos-col-action .btn{
                padding: 4px 10px;
            }

            .produtos-action-create{
                padding: 4px 10px;
                float: right;
                margin-top: -5px;
            }

        </style>

        <!-- Scripts -->
        <script type="text/javascript" src="<?=$baseUri ?>js/jquery-2.1.4.min.js"></script>
        <script type="text/javascript" src="<?=$baseUri ?>js/bootstrap.min.js"></script>
    </head>
    <body>
        <nav class="navbar navbar-default">
            <div class="container-fluid">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-links" aria-expanded="false">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="#">Brand</a>
                </div>
                <div class="collapse navbar-collapse" id="navbar-links">
                    <ul id="navbar-links-container" class="nav navbar-nav navbar-left">
                        <?php foreach($menus as $item) : ?>
                            <li <?=$item['actived'] ? 'class="active"' : ''?>>
                                <a href="<?=$item['url'] ?>"><?=$item['label'] ?></a>
                            </li>
                        <?php endforeach; ?>
                    </ul>
                </div>
            </div>
        </nav>
        <div class="container">
            <?=$this->content ?>
        </div>
    </body>
</html>
